name: Feature Request
description: Suggest an idea for this project
title: "[Feature Request]"
labels: ["feature request"]
projects: ["GregoryAM-SP/9"]
assignees:
  - Gregory-AM

body:
  - type: markdown
    attributes:
      value: |
        ### Guidelines:
        - Be clear and concise about the feature.
        - Explain why this feature would be beneficial.
  
  - type: textarea
    id: description
    attributes:
      label: Feature description
      description: A clear and concise description of the feature you're suggesting.
    validations:
      required: true